#Service ID
dismiss_alert:
  name: Dismiss alert
  description: Dismiss an alert
  target:
    entity:
      integration: lintkap
      domain: binary_sensor

dismiss_alerts:
  name: Dismiss Alerts
  description: Dismiss all alerts
  target:
    entity:
      integration: linktap
      domain: binary_sensor

pause:
  name: Pause
  description: Pause the watering
  fields:
    duration:
      example: 1
      description: Duration in hours
  target:
    entity:
      integration: linktap
      domain: switch
